Mobile 4279
moodlehq/moodlemobile2 pull request #3581
Opened 2023-03-16 11:18 UTC by crazyserver

2023-03-17 08:10 UTC, dpalou requested changes

2023-03-17 08:10 UTC, dpalou commented on src/core/directives/fa-icon.ts
> +            return;
IMO this can cause problems. E.g. if the read file is in progress you will have an empty list of aliases but `readIconsJson` will resolve immediately.

IMO it's better to use a `CorePromisedValue` here. Something like:

```
protected static aliases: CorePromisedValue<Record<string, string>>;

...

protected async checkIconAlias(iconName: string): Promise<string> {
    const aliases = await CoreFaIconDirective.aliases;
    if (aliases[iconName]) {
    ...
}
```

The implementation of `readIconsJson` would be quite similar to the current one, but resolving the `CorePromisedValue` when the file has been loaded. If the file fails to load we should probably display an error in console and resolve with an empty list of aliases.

I couldn't use the suggestion tool because your PR is too big and the "Files" tab freezes.

2023-03-17 08:11 UTC, dpalou commented
Besides the comment above, can you add a note in upgrade.txt specifying that Font-Awesome has been updated? IMO it'd be nice to specify that old icon names will still work but it's recommended to update them to the new names.

2023-03-20 10:56 UTC, crazyserver commented
Thanks Dani! Solved!

2023-03-21 09:39 UTC, dpalou requested changes

2023-03-21 09:39 UTC, dpalou commented on src/core/directives/fa-icon.ts
> +    protected static async readIconsJson(): Promise<Record<string, string>> {
Isn't "protected static" a bit weird? Shouldn't it be just "static"?

2023-03-21 09:39 UTC, dpalou commented on src/core/directives/fa-icon.ts
> +    protected static async readIconsJson(): Promise<Record<string, string>> {
Also, I think it would be better to name this function "getIconsAliases" or something like this, it's easier to understand what it does.

2023-03-21 09:39 UTC, dpalou commented on src/core/directives/fa-icon.ts
> +        const request = await Http.get('assets/fonts/font-awesome/aliases.json', {
I think you can specify the return type: `Http.get<Record<string, string>>`. That way you don't need to cast it later.

2023-03-21 09:39 UTC, dpalou commented on src/core/directives/fa-icon.ts
> +        const request = await Http.get('assets/fonts/font-awesome/aliases.json', {
IMO this variable should be called `aliases`, you're doing an await so the variable will hold the result of the request, it's not the request promise.

2023-03-21 09:39 UTC, dpalou commented on src/core/directives/fa-icon.ts
> +        CoreFaIconDirective.aliases.resolve(request as Record<string, string>);
I know it shouldn't happen, but if the read file fails the `CorePromisedValue` will never be resolved. I think it'd be better to have a `catch`, and if the request fails then we can resolve the aliases with an empty object.

2023-03-21 09:39 UTC, dpalou commented on src/core/directives/fa-icon.ts
> +        return CoreFaIconDirective.aliases;
Here you already have the list of aliases (because you did an `await`), so I'd just return them instead of returning the `CorePromisedValue`.

2023-03-21 11:52 UTC, dpalou approved these changes

2023-03-21 11:53 UTC, merged