Mobile 4499
moodlehq/moodlemobile2 pull request #3934
Opened 2024-02-20 07:12 UTC by dpalou

2024-02-21 13:51 UTC, crazyserver requested changes

2024-02-21 13:51 UTC, crazyserver commented on src/addons/calendar/pages/event/event.ts
> +    protected appResumeSubscription: Subscription;
Just a personal thing: Add subscriptions array and observers array to then turn them off altogether on destroy.

2024-02-21 13:51 UTC, crazyserver commented on src/addons/notifications/pages/list/list.ts
> +    protected appResumeSubscription?: Subscription;
Same (array thing)

2024-02-21 13:51 UTC, crazyserver commented on src/theme/theme.base.scss
> +        @include margin(0, 8px, 8px, 8px);
Since start and end (left and right) is the same, use margin: directly without the include.

2024-02-22 08:40 UTC, dpalou commented on src/theme/theme.base.scss
> +        @include margin(0, 8px, 8px, 8px);
Changed (the CSS was included in the previous issue though, but I fixed it here).

2024-02-22 08:48 UTC, crazyserver approved these changes

2024-02-22 08:49 UTC, merged