Mobile 4539
moodlehq/moodlemobile2 pull request #3959
Opened 2024-03-07 12:35 UTC by dpalou

2024-03-08 14:42 UTC, crazyserver requested changes

2024-03-08 14:42 UTC, crazyserver commented on src/core/services/file-helper.ts
> +        state?: TDownloadStatus,
Based on changes on jsdocs of this function... did you want this to be renamed as status?

2024-03-08 14:42 UTC, crazyserver commented on src/core/services/file-helper.ts
> +        state?: TDownloadStatus,
Same rename thing? There are lots, so probably you dont' want to make it...

2024-03-11 07:06 UTC, dpalou commented on src/core/services/file-helper.ts
> +        state?: TDownloadStatus,
In some places we call it "state", in some others we call it "status". One of the definitions I found is:

State: the particular condition that someone or something is in at a specific time. Status: the situation at a particular time during a process. **They can be used in similar ways**.

Based on this definition, IMO it's ok to have both words.

Some people said that there's a small difference (e.g. one of them being "final" and the other being the condition during a process), but some pages said that "status" is the final condition while others said that state was the final condition ^^'

2024-03-11 10:29 UTC, dpalou commented on src/core/services/file-helper.ts
> +        state?: TDownloadStatus,
Sorry, I didn't understand you. I reverted the JSDoc change.

2024-03-11 10:42 UTC, crazyserver approved these changes

2024-03-11 10:53 UTC, merged