Mobile 4572
moodlehq/moodlemobile2 pull request #4005
Opened 2024-04-10 14:12 UTC by dpalou

2024-04-10 14:31 UTC, crazyserver requested changes

2024-04-10 14:31 UTC, crazyserver commented on src/core/features/login/components/login-methods/login-methods.ts
> +        const modal = await CoreDomUtils.showModalLoading();
What to you think about including the modal and errors inside the helper functions this way it's not necessary to replacate all that code every time.

2024-04-11 06:30 UTC, dpalou commented on src/core/features/login/components/login-methods/login-methods.ts
> +        const modal = await CoreDomUtils.showModalLoading();
Done!

2024-04-11 06:57 UTC, crazyserver approved these changes

2024-04-11 06:57 UTC, merged